version: '3'
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    command: sh -c "node index.js"
    depends_on: 
      - redis

  redis:
    image: redis:alpine
    expose:
      - 6379