version: '3'
services:
  automatization:
    build: 
      context: .
      dockerfile: Dockerfile
    command: sh -c "node index.js"
    network_mode: host
    depends_on: 
      - redis
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
