apiVersion: apps/v1
kind: Deployment
metadata:
  name: automator
  labels:
    app: automator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: automator
  template:
    metadata:
      labels:
        app: automator
    spec:
      containers:
      - name: automator
        image: 437642595153.dkr.ecr.sa-east-1.amazonaws.com/automator:v3
        env:
        - name: AWS_ACCESS_KEY
          value: ""
        - name: AWS_SECRET_ACCESS_KEY
          value: ""
        - name: AWS_DEFAULT_REGION
          value: "sa-east-1"
        - name: NODE_ENV
          value: "qa"
        ports:
        - containerPort: 3009
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30